<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;

class ContentTypeSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		DB::table('content_types')->insert([
			[
				'order'				=> 1,
				'singular'		=> 'User',
				'plural'			=> 'Users',
				'icon'				=> 'fa-users',
				'slug'				=> 'users',
				'route'				=> 'list',
				'desc'				=> 'Manage all frontend & backend users',
				'category_id'	=> 1,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 2,
				'singular'		=> 'Menu',
				'plural'			=> 'Menus',
				'icon'				=> 'fa-list-dropdown',
				'slug'				=> 'menus',
				'route'				=> 'menus',
				'desc'				=> 'Frontend navigation structures',
				'category_id'	=> 1,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 3,
				'singular'		=> 'Content Type',
				'plural'			=> 'Content Types',
				'icon'				=> 'fa-chart-tree-map',
				'slug'				=> 'content-types',
				'route'				=> 'list',
				'desc'				=> 'Manage frontend & backend content types',
				'category_id'	=> 1,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 4,
				'singular'		=> 'Option',
				'plural'			=> 'Options',
				'icon'				=> 'fa-gears',
				'slug'				=> 'options',
				'route'				=> 'options',
				'desc'				=> 'Manage all frontend & backend options',
				'category_id'	=> 1,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 1,
				'singular'		=> 'Page',
				'plural'			=> 'Pages',
				'icon'				=> 'fa-files',
				'slug'				=> 'pages',
				'route'				=> 'list',
				'desc'				=> 'Static content pages',
				'category_id'	=> 2,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 2,
				'singular'		=> 'Post',
				'plural'			=> 'Posts',
				'icon'				=> 'fa-typewriter',
				'slug'				=> 'posts',
				'route'				=> 'list',
				'desc'				=> 'Share news, updates, and ideas for your audience through a blog',
				'category_id'	=> 2,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 3,
				'singular'		=> 'Section',
				'plural'			=> 'Sections',
				'icon'				=> 'fa-diagram-cells',
				'slug'				=> 'sections',
				'route'				=> 'list',
				'desc'				=> 'Pre-defined content layouts that can be re-used',
				'category_id'	=> 2,
				'protected'		=> true,
				'required'		=> true,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 4,
				'singular'		=> 'FAQ',
				'plural'			=> 'FAQS',
				'icon'				=> 'fa-block-question',
				'slug'				=> 'faqs',
				'route'				=> 'list',
				'desc'				=> 'All your frequently asked questions and answers in one place',
				'category_id'	=> 2,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 5,
				'singular'		=> 'Testimonial',
				'plural'			=> 'Testimonials',
				'icon'				=> 'fa-square-quote',
				'slug'				=> 'testimonials',
				'route'				=> 'list',
				'desc'				=> 'Share what people are saying about you',
				'category_id'	=> 2,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 1,
				'singular'		=> 'Trip',
				'plural'			=> 'Trips',
				'icon'				=> 'fa-earth-americas',
				'slug'				=> 'trips',
				'route'				=> 'list',
				'desc'				=> 'Create and manage all your mission trips',
				'category_id'	=> 3,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 2,
				'singular'		=> 'Group',
				'plural'			=> 'Groups',
				'icon'				=> 'fa-users-viewfinder',
				'slug'				=> 'groups',
				'route'				=> 'list',
				'desc'				=> 'Create and manage all your groups',
				'category_id'	=> 3,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 3,
				'singular'		=> 'Participant',
				'plural'			=> 'Participants',
				'icon'				=> 'fa-id-badge',
				'slug'				=> 'participants',
				'route'				=> 'list',
				'desc'				=> 'Manage individual registrants',
				'category_id'	=> 3,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 1,
				'singular'		=> 'Payment',
				'plural'			=> 'Payments',
				'icon'				=> 'fa-credit-card',
				'slug'				=> 'payments',
				'route'				=> 'list',
				'desc'				=> 'Manage payments for trips',
				'category_id'	=> 4,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 2,
				'singular'		=> 'Donation',
				'plural'			=> 'Donations',
				'icon'				=> 'fa-gift',
				'slug'				=> 'donations',
				'route'				=> 'list',
				'desc'				=> 'Manage donations',
				'category_id'	=> 4,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
			[
				'order'				=> 3,
				'singular'		=> 'Subscriber',
				'plural'			=> 'Subscribers',
				'icon'				=> 'fa-envelopes-bulk',
				'slug'				=> 'subscribers',
				'route'				=> 'list',
				'desc'				=> 'Manage mailing list subscribers',
				'category_id'	=> 4,
				'protected'		=> false,
				'required'		=> false,
				'created_at'	=> Carbon::now(),
				'updated_at'	=> Carbon::now(),
			],
		]);
	}
}
