<?php

return json_decode(json_encode([
	// USERS
	'users' => [
		'columns' => [
			'template' => 'grid-cols-[24px_auto_150px_150px]',
			'items' => [
				[
					'text' => 'ID',
					'key' => '',
					'type' => 'id',
					'class' => 'text-center uppercase',
				],
				[
					'text' => 'Name',
					'key' => 'name',
					'type' => 'main',
					'class' => '',
				],
				[
					'text' => 'Role',
					'key' => '',
					'type' => 'user_role',
					'class' => 'text-center',
				],
				[
					'text' => 'Actions',
					'key' => '',
					'type' => 'actions',
					'class' => 'text-center',
				],
			],
		],
		'fields' => [
			[
				'forms' => ['create', 'edit'],
				'order' => 1,
				'type' => 'title',
				'class' => '',
				'id' => 'name',
				'key' => 'name',
				'label' => 'Name',
				'placeholder' => 'John Doe',
				'desc' => '',
				'required' => true,
				'validate' => [
					'store' => 'required',
					'update' => 'required',
				],
			],
			[
				'forms' => ['create', 'edit'],
				'order' => 2,
				'type' => 'string',
				'class' => '',
				'id' => 'email',
				'key' => 'email',
				'label' => 'Email / Username',
				'placeholder' => 'john@example.com',
				'desc' => '',
				'required' => true,
				'validate' => [
					'store' => 'required|unique:App\Models\User,email',
					'update' => 'required',
				],
			],
			[
				'forms' => ['edit'],
				'order' => 3,
				'type' => 'password',
				'class' => '',
				'id' => 'current_pass',
				'key' => '',
				'label' => 'Current Password',
				'placeholder' => 'Current Password',
				'desc' => '',
				'required' => false,
				'validate' => [
					'store' => '',
					'update' => 'required_with_all:new_pass,confirm_pass|current_password:web',
				],
			],
			[
				'forms' => ['edit'],
				'order' => 4,
				'type' => 'password',
				'class' => '',
				'id' => 'new_pass',
				'key' => 'password',
				'label' => 'New Password',
				'placeholder' => 'New Password',
				'desc' => '',
				'required' => false,
				'validate' => [
					'store' => '',
					'update' => 'required_with_all:current_pass,confirm_pass',
				],
			],
			[
				'forms' => ['edit'],
				'order' => 5,
				'type' => 'password',
				'class' => '',
				'id' => 'confirm_pass',
				'key' => '',
				'label' => 'Confirm New Password',
				'placeholder' => 'Confirm New Password',
				'desc' => '',
				'required' => false,
				'validate' => [
					'store' => '',
					'update' => 'required_with_all:current_pass,new_pass|same:new_pass',
				],
			],
			[
				'forms' => ['create'],
				'order' => 5,
				'type' => 'password',
				'class' => '',
				'id' => 'password',
				'key' => 'password',
				'label' => 'Password',
				'placeholder' => 'Password',
				'desc' => '',
				'required' => true,
				'validate' => [
					'store' => 'required',
					'update' => '',
				],
			],
			[
				'forms' => ['create'],
				'order' => 6,
				'type' => 'password',
				'class' => '',
				'id' => 'confirm_pass',
				'key' => '',
				'label' => 'Confirm Password',
				'placeholder' => 'Confirm Password',
				'desc' => '',
				'required' => true,
				'validate' => [
					'store' => 'required|same:password',
					'update' => '',
				],
			],
		],
	],

	// MENUS
	'menus' => [
		'columns' => [],
		'fields' => [],
	],

	// COLLECTION TYPES
	'collection-types' => [
		'columns' => [
			'template' => 'grid-cols-[24px_75px_auto_150px_150px_150px]',
			'items' => [
				[
					'text' => 'ID',
					'key' => 'id',
					'type' => 'id',
					'class' => 'text-center uppercase',
				],
				[
					'icon' => 'fa-icons',
					'key' => 'icon',
					'type' => 'icon',
					'class' => 'text-center',
				],
				[
					'text' => 'Name',
					'key' => 'label',
					'type' => 'main',
					'class' => '',
				],
				[
					'text' => 'Category',
					'key' => 'category',
					'type' => 'category',
					'class' => 'text-center',
				],
				[
					'text' => 'Slug',
					'key' => 'slug',
					'type' => 'slug',
					'class' => 'text-center',
				],
				[
					'text' => 'Actions',
					'key' => '',
					'type' => 'actions',
					'class' => 'text-center',
				],
			],
		],
		'fields' => [
			[
				'forms' => ['create', 'edit'],
				'order' => 1,
				'type' => 'integer',
				'class' => '',
				'id' => 'order',
				'key' => 'order',
				'label' => 'Menu Order',
				'placeholder' => '1',
				'desc' => '',
				'required' => true,
				'validate' => [
					'store' => 'required|integer',
					'update' => 'required|integer',
				],
			],
			[
				'forms' => ['create', 'edit'],
				'order' => 2,
				'type' => 'string',
				'class' => '',
				'id' => 'label',
				'key' => 'label',
				'label' => 'Singular Label',
				'placeholder' => 'Singular Label',
				'desc' => 'The singular form of the label you wish to use. (i.e. Item vs Items)',
				'required' => true,
				'validate' => [
					'store' => 'required',
					'update' => 'required',
				],
			],
			[
				'forms' => ['create', 'edit'],
				'order' => 3,
				'type' => 'string',
				'class' => '',
				'id' => 'icon',
				'key' => 'icon',
				'label' => 'Icon',
				'placeholder' => 'fa-user-circle',
				'desc' => 'The Font Awesome icon identifier.',
				'required' => true,
				'validate' => [
					'store' => 'required',
					'update' => 'required',
				],
			],
			[
				'forms' => ['create', 'edit'],
				'order' => 4,
				'type' => 'string',
				'class' => '',
				'id' => 'slug',
				'key' => 'slug',
				'label' => 'Slug',
				'placeholder' => 'slug',
				'desc' => 'Usually the plural form of the label, but it can be whatever you would like. Needs to be unique from any other collection type slug.',
				'required' => true,
				'validate' => [
					'store' => 'required|unique:App\Models\CollectionType,slug',
					'update' => 'required',
				],
			],
			[
				'forms' => ['create', 'edit'],
				'order' => 5,
				'type' => 'text',
				'class' => '',
				'id' => 'desc',
				'key' => 'desc',
				'label' => 'Description',
				'placeholder' => 'Description',
				'desc' => '',
				'required' => false,
				'validate' => [
					'store' => '',
					'update' => '',
				],
			],
			[
				'forms' => ['create', 'edit'],
				'order' => 6,
				'type' => 'category',
				'class' => '',
				'id' => 'category_id',
				'key' => 'category_id',
				'label' => 'Category',
				'placeholder' => 'Please select one',
				'desc' => '',
				'required' => true,
				'catType' => 'collection-type',
				'validate' => [
					'store' => 'required',
					'update' => 'required',
				],
			],
		],
	],

	//CATEGORIES
	'categories' => [
		'columns' => [
			'template' => 'grid-cols-[24px_auto_150px_150px_150px]',
			'items' => [
				[
					'text' => 'ID',
					'key' => 'id',
					'type' => 'id',
					'class' => 'text-center uppercase',
				],
				[
					'text' => 'Name',
					'key' => 'label',
					'type' => 'main-plural',
					'class' => '',
				],
				[
					'text' => 'Type',
					'key' => 'type',
					'type' => 'default',
					'class' => 'text-center text-sm',
				],
				[
					'text' => 'Slug',
					'key' => 'slug',
					'type' => 'slug',
					'class' => 'text-center',
				],
				[
					'text' => 'Actions',
					'key' => '',
					'type' => 'actions',
					'class' => 'text-center',
				],
			],
		],
		'fields' => [],
	],

	// OPTIONS
	'options' => [
		'columns' => [],
		'fields' => [],
	],

	// DEFAULT
	'default' => [
		'columns' => [
			'template' => 'grid-cols-[24px_auto_150px]',
			'items' => [
				[
					'text' => 'ID',
					'key' => 'id',
					'type' => 'id',
					'class' => 'text-center uppercase',
				],
				[
					'text' => 'Title',
					'key' => 'title',
					'type' => 'main',
					'class' => '',
				],
				[
					'text' => 'Actions',
					'key' => '',
					'type' => 'actions',
					'class' => 'text-center',
				],
			],
		],
		'fields' => [],
	],
]));

// TESTIMONIALS - COLUMNS
// 'template' => 'grid-cols-[24px_150px_150px_auto_150px]',
// 'items' => [
// 	[
// 		'text' => 'ID',
// 		'key' => 'id',
// 		'type' => 'id',
// 		'class' => 'text-center uppercase',
// 	],
// 	[
// 		'text' => 'Author',
// 		'key' => 'author',
// 		'type' => 'main',
// 		'class' => '!text-center',
// 	],
// 	[
// 		'text' => 'Trip',
// 		'key' => 'trip',
// 		'type' => 'default',
// 		'class' => 'text-center',
// 	],
// 	[
// 		'text' => 'Quote',
// 		'key' => 'quote',
// 		'type' => 'text',
// 		'class' => 'text-sm',
// 	],
// 	[
// 		'text' => 'Actions',
// 		'key' => '',
// 		'type' => 'actions',
// 		'class' => '',
// 	],
// ],

// TESTIMONIALS - FIELDS
// [
// 	'order' => 1,
// 	'type' => 'title',
// 	'class' => '',
// 	'id' => 'title',
// 	'key' => 'fields',
// 	'label' => 'Title',
// 	'placeholder' => 'Content Title',
// 	'desc' => '',
// 	'required' => true,
// 	'validate' => '',
// ],
// [
// 	'order' => 2,
// 	'type' => 'fulltext',
// 	'class' => '',
// 	'id' => 'quote',
// 	'key' => 'fields',
// 	'label' => 'Quote',
// 	'placeholder' => 'For many of us, inspiration is triggered by the quips and quotations of others.',
// 	'desc' => '',
// 	'required' => true,
// 	'validate' => '',
// ],
// [
// 	'order' => 3,
// 	'type' => 'string',
// 	'class' => '',
// 	'id' => 'author',
// 	'key' => 'fields',
// 	'label' => 'Author',
// 	'placeholder' => 'Emilee Day',
// 	'desc' => '',
// 	'required' => true,
// 	'validate' => '',
// ],
// [
// 	'order' => 4,
// 	'type' => 'string',
// 	'class' => '',
// 	'id' => 'trip',
// 	'key' => 'fields',
// 	'label' => 'Trip',
// 	'placeholder' => 'Location YYYY',
// 	'desc' => '',
// 	'required' => true,
// 	'validate' => '',
// ],